export const mermaid = `graph TD
    A[Start] --> B[Enter Site]
    B --> C[Dashboard]
    
    subgraph User
        C --> E[Edit Markdown/Mermaid Files]
        C --> G[Download Chart/Markdown]
        C --> H[View Saved Projects]
    end
    
    B --> I[Sign Up/Login]
    
    subgraph Registered User
        I --> J[Use Mermaid Mind AI]
    end

    E --> O[Enter/Edit Markdown or Mermaid Code]
    O --> P[Preview Changes]
    P --> Q[Save Changes]

    G --> R[Select Chart Format PNG/SVG or Markdown .md]
    R --> S[Download File]

    H --> V[Select Project]
    V --> W[View Charts/Markdown in Project]

    J --> X[Get AI-Generated Mermaid Code/Markdown]
    X --> Y[Edit AI-Generated Code]
    Y --> Z[Save AI-Generated Content]
`;

export const markdown = `# Welcome to Mermaid Mind

## Features

### Dashboard
- **Edit Markdown/Mermaid Files**: Modify and preview your markdown or mermaid diagram code.
- **Download Chart/Markdown**: Export your diagrams as PNG/SVG or markdown files.
- **View Saved Projects**: Access your previously saved projects and their associated charts or markdown files.

### User Authentication
- **Sign Up/Login**: Create an account or log in to access additional features.
- **Use Mermaid Mind AI**: Registered users can leverage AI to generate mermaid code or markdown.

### Editing and Preview
- **Enter/Edit Markdown or Mermaid Code**: Start typing your code and see real-time updates.
- **Preview Changes**: Instantly preview the changes made to your code.
- **Save Changes**: Save your modifications for future use.

### Downloading
- **Select Chart Format**: Choose between PNG, SVG, or Markdown formats.
- **Download File**: Download your work in the selected format.

### Project Management
- **Select Project**: Choose a project to view or edit.
- **View Charts/Markdown in Project**: See all the diagrams and markdown files within a selected project.

### AI-Powered Features
- **Get AI-Generated Mermaid Code/Markdown**: Use our AI to generate code or markdown content.
- **Edit AI-Generated Code**: Fine-tune the AI-generated content to fit your needs.
- **Save AI-Generated Content**: Save the content generated by the AI for future use.

## Example Usage

### Creating a Mermaid Diagram

1. Navigate to the **Dashboard**.
2. Click on **Edit Markdown/Mermaid Files**.
3. Enter your mermaid code:

4. Click on **Preview Changes** to see your diagram.
5. Once satisfied, click **Save Changes**.

### Downloading Your Work

1. Go to **Download Chart/Markdown** in the **Dashboard**.
2. Select the format (PNG, SVG, or .md).
3. Click **Download File** to save it to your device.

### Using Mermaid Mind AI

1. Sign up or log in.
2. Navigate to **Use Mermaid Mind AI**.
3. Enter a prompt for the type of diagram or markdown you need.
4. Review the AI-generated code.
5. Edit if necessary and save the content.

## Conclusion

Enjoy using Mermaid Mind to create, edit, and manage your markdown and mermaid diagram files with ease. Our AI features will help you streamline your workflow and produce high-quality content effortlessly.

`;
